// app/layout.js
import "./globals.css";
import BottomNavbar from "@/components/BottomNavbar/BottomNavbar";
import ClientProvider from "@/components/ClientProvider/ClientProvider";
import { ImageDataProvider } from "@/context/ImageDataContext";
import { Poppins } from "@next/font/google";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "500", "700"], // Specify the weights you need
});

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            {/* <html lang="en" className={poppins.className}> */}
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />

                {/* <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" /> */}
            </head>
            <body className="bg-[#efefef]">
                <ClientProvider>
                    <ImageDataProvider>
                        {children}
                        <BottomNavbar />
                    </ImageDataProvider>
                </ClientProvider>
            </body>
        </html>
    );
}
