// import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import "./globals.css";
import BottomNavbar from "@/components/BottomNavbar/BottomNavbar";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="bg-[#efefef]">
                {children}
                <BottomNavbar />
            </body>
        </html>
    );
}
